# yamllint disable rule:document-start
# yamllint disable rule:line-length
# Automatically stale old issues and PRs which didn't receive any update, following an explicit feedback request
# (marked by the 'status - waiting for feedback' label)
name: Stale

'on':
  schedule:
    - cron: '1 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: 90 days stale policy for issues & PRs
        uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 90
          days-before-close: 14
          only-labels: 'status - waiting for feedback'
          remove-stale-when-updated: true
          stale-issue-label: 'stale'
          exempt-issue-labels: 'no-stale,help-wanted'
          stale-issue-message: |
            Hi,

            there hasn't been any activity on this issue recently. Due to the high number of incoming tickets, we have to clean some of the old issues which didn't receive any update from the people involved, following a feedback request.
            Please make sure to update to the latest version. Let us know if that works for you by adding a comment. üëç

            This issue has now been marked as stale and will be closed if no further activity occurs within 14 days.

            Thank you for your precious contribution. üöÄ
          stale-pr-label: 'stale'
          exempt-pr-labels: 'no-stale, help-wanted'
          stale-pr-message: |
            Hi,

            There hasn't been any activity on this pull request recently. Due to the high number of incoming tickets, we have to clean some of the old pull requests which didn't receive any update from the people involved, following a feedback request.

            This pull request has been automatically marked as stale and will be closed if no further activity occurs within 14 days.

            Thank you for your precious contribution. üöÄ
